[dependencies]
proc-macro2 = "1"
quote = { version = "1" }
syn = { version = "2", features = ["full"] }

[lib]
path = "Source/lib.rs"
proc-macro = true

[package]
edition = "2021"
license-file = "LICENSE"
name = "nsis-fn"
version = "0.0.0"
