[dependencies]
nsis-fn = { path = "../nsis-fn" }
windows-sys = { workspace = true }

[lib]
path = "Source/lib.rs"

[package]
edition = "2021"
license-file = "LICENSE"
name = "nsis-plugin-api"
version = "0.0.0"
